//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNet.Modele
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public int IdEt { get; set; }
        public string CIN { get; set; }
        public string Nom { get; set; }
        public string Prénom { get; set; }
        public string ClasseIdCl { get; set; }
    
        public virtual Classe Classe { get; set; }
    }
}
